// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEa1DMUg5fMID7s92mrqc36rCy9FSv8qY',
    appId: '1:340407306537:web:e09ea1e8ea9cb5cbb9cf38',
    messagingSenderId: '340407306537',
    projectId: 'slumber-c379b',
    authDomain: 'slumber-c379b.firebaseapp.com',
    storageBucket: 'slumber-c379b.firebasestorage.app',
    measurementId: 'G-HNB8VK0VSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADS7-8xmWtmAeGsx8Oa9vTkiDv4xtDh8Y',
    appId: '1:340407306537:android:dd296b99ba425a0eb9cf38',
    messagingSenderId: '340407306537',
    projectId: 'slumber-c379b',
    storageBucket: 'slumber-c379b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMO10eme0nQhT0ccBzNMogMvdR0IfTWts',
    appId: '1:340407306537:ios:d977e9f0d2f144cbb9cf38',
    messagingSenderId: '340407306537',
    projectId: 'slumber-c379b',
    storageBucket: 'slumber-c379b.firebasestorage.app',
    iosBundleId: 'com.slumber.slumber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMO10eme0nQhT0ccBzNMogMvdR0IfTWts',
    appId: '1:340407306537:ios:d977e9f0d2f144cbb9cf38',
    messagingSenderId: '340407306537',
    projectId: 'slumber-c379b',
    storageBucket: 'slumber-c379b.firebasestorage.app',
    iosBundleId: 'com.slumber.slumber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEa1DMUg5fMID7s92mrqc36rCy9FSv8qY',
    appId: '1:340407306537:web:9d271778bc8404f3b9cf38',
    messagingSenderId: '340407306537',
    projectId: 'slumber-c379b',
    authDomain: 'slumber-c379b.firebaseapp.com',
    storageBucket: 'slumber-c379b.firebasestorage.app',
    measurementId: 'G-5EXPZCFKC8',
  );
}
